# db.py
from supabase import create_client
import streamlit as st

# Use your Supabase keys
SUPABASE_URL = "https://mfkpehvnvbgarorakerg.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ma3BlaHZudmJnYXJvcmFrZXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NjIxMTMsImV4cCI6MjA4NjUzODExM30.Ju4l3Zp6jCAOclcXfx-CLeAxF9rom91iTF9K92yXLe0"

# Optional: service role if you need server-side admin operations
SUPABASE_SERVICE_ROLE = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ma3BlaHZudmJnYXJvcmFrZXJnIiwicm9sZSIsInNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MDk2MjExMywiZXhwIjoyMDg2NTM4MTEzfQ.nLcQIF8P5RHNK3mJPwJPzrqOIDxLkLXOTjGMRoeabTM"

# Create Supabase client
supabase = create_client(SUPABASE_URL, SUPABASE_ANON_KEY)
